shell.execute("delete", "/programfiles/hexget")
shell.execute("wget", "https://raw.githubusercontent.com/Shirtsy/HexLator/main/hexlator.lua", "/programfiles/hexlator/hexlator.lua")
shell.execute("wget", "https://raw.githubusercontent.com/Shirtsy/HexLator/main/hexget.lua", "/programfiles/hexlator/hexget.lua")
shell.execute("wget", "https://raw.githubusercontent.com/Shirtsy/HexLator/main/symbol-registry.json", "/programfiles/hexlator/symbol-registry.json")
shell.execute("wget", "https://raw.githubusercontent.com/Shirtsy/HexLator/main/hexxyedit.lua", "/programfiles/hexlator/hexxyedit.lua")
shell.execute("mkdir", "/programfiles/hexlator/lib")
shell.execute("delete", "/startup.lua")
local file = fs.open("startup.lua","w")
file.write('shell.setAlias("hexget", "/programfiles/hexlator/hexget.lua") shell.setAlias("hexxyedit", "/programfiles/hexlator/hexxyedit.lua")')
file.close()
os.reboot()
