shell.execute("delete", "/programfiles/hexget")
shell.execute("wget", "https://raw.githubusercontent.com/Shirtsy/Hexpiler/main/hexpiler.lua", "/programfiles/hexget/hexpiler.lua")
shell.execute("wget", "https://raw.githubusercontent.com/Shirtsy/Hexpiler/main/hexget.lua", "/programfiles/hexget/hexget.lua")
shell.execute("wget", "https://raw.githubusercontent.com/Shirtsy/Hexpiler/main/symbol-registry.json", "/programfiles/hexget/symbol-registry.json")
shell.execute("delete", "/startup.lua")
local file = fs.open("startup.lua","w")
file.write('shell.setAlias("hexget", "/programfiles/hexget/hexget.lua")')
file.close()
os.reboot()
